### ISSUE TITLE
Repeated Update Available :Pi Support Plugin: 2022.3.1

### ISSUE THREAD

**Issue by ProtomakerSprint** [OctoPrint/OctoPrint-PiSupport#10]
Repeated Update Available

Even after updating and resetting

Update Available
There are updates available for the following components:
Pi Support Plugin: 2022.3.1
[Release Notes](https://github.com/OctoPrint/OctoPrint-PiSupport/releases/tag/2022.3.1)

Also Now don't know how to Fix this:
Cannot check for throttling
OctoPrint cannot check for throttling situations reported by your Pi. vcgencmd doesn't work as expected. Make sure the system user OctoPrint is running under is a member of the "video" group.

**Comment by cp2004** [comment]
We need a systeminfo bundle to look into the issue at all, please provide one - upload the whole zip file, to GitHub as an attachment.

**Comment by foosel** [comment]
Closing issue due to lack of information.
