### ISSUE TITLE
Pi support tries to get loaded even though not on rasberry pi

### ISSUE THREAD

**Issue by nionio6915** [OctoPrint/OctoPrint-PiSupport#13]
hi  - 
i am running armbian on oragepi zero. I had to restore from backup. the new image keeps failing back into safe mode. the only thing obvious in the logs is Pi Support.  

'2022-05-31 19:55:23,323 - octoprint.plugin.core - INFO - Plugin Pi Support Plugin (2022.3.28) did not pass check, not loading."

Pi Support Plugin keeps trying to load. 

What/wehre is the check for OS/Hardware?

**Comment by jneilliii** [comment]
The entry indicates it's not loading after determining it's not running on a pi. You can disable the plugin in plugin manager to completely rule that out though. I would say there is something else causing the trouble. Have you tried booting octoprint into safe mode?

**Comment by foosel** [comment]
I fear without a log there's nothing to be done about this ticket then, considering that you now also have reflashed. The plugin not passing the check is certainly not what made your startup fail, as pointed out by @jneilliii this line is normal if run on systems that aren't RPis and won't interfere with startup at all. Closing as not actionable.
