### ISSUE TITLE
"/usr/bin/vcgencmd get_throttled" doesn't work

### ISSUE THREAD

**Issue by olli-e** [OctoPrint/OctoPrint-PiSupport#4]
Hi there,

I am not sure if this is a plugin issue, but this warning is written repeatedly in the octoprint logfile:

octoprint.plugins.pi_support - WARNING - Fetching the current throttle state via "/usr/bin/vcgencmd get_throttled" doesn't work

I have made sure that the user is able to sudo and can execute the command just fine on the console - but with the sudo infront of it.

Do I have to enable the user to issue this command without sudo?

Thanks and best regards,
Oliver

**Comment by foosel** [comment]
`sudo` is not needed for the command to work. Please share a [systeminfo bundle](https://community.octoprint.org/t/what-is-a-systeminfo-bundle-and-how-can-i-obtain-one/29887) and also run `/usr/bin/vcgencmd get_throttled` via SSH and then share its output.

**Comment by olli-e** [comment]
Oh, whatever I did, now sudo is no longer required....strange, before it was. However, the error is gone, thanks anyway!

**Comment by sur5r** [comment]
As promised during rc3, I checked my octoprint instance again and found that I still need `sudo` for `vcgencmd` to work.

```
root@octoprint:~# /usr/bin/vcgencmd get_throttled
throttled=0x0
root@octoprint:~# su - octoprint -c "/usr/bin/vcgencmd get_throttled"
VCHI initialization failed
root@octoprint:~# 
```

This is a Raspbian/RaspiOS installed as buster which has been updated to bullseye.

However, I found this: https://chewett.co.uk/blog/258/vchi-initialization-failed-raspberry-pi-fixed/

So adding the `octoprint` user to the `video` group solves this.

**Comment by foosel** [comment]
@sur5r thanks for the follow-up! I actually also still have the TODO on my whiteboard that I added after our chat at RC3 :D

I might be able to react to the `VCHI initialization failed` message here and then show instructions on what to do.
